@startuml Diagrama de Estado Proyecto
state c1 <<choice>>
state c2 <<choice>>
state c3 <<choice>>
state c4 <<choice>>
state c5 <<choice>>
state c6 <<choice>>
state c7 <<choice>>

[*] --> Entrar_plataforma: Iniciar espacio virtual
Entrar_plataforma-->c1:Registrar?
c1-->Ingresar_datos :si
c1-->Iniciar_sesión :no
Ingresar_datos-->Iniciar_sesión
Iniciar_sesión-->c2:Consultar publicaciones?
c2-->Visualizar_publicaciones :si
c2--> Añadir_publicaciones :no
Visualizar_publicaciones-->c3:Comentar?
c3-->Notificación_de_publicación :si
c3-->Visualizar_publicaciones :no
Notificación_de_publicación-->c4:Eventos revisados?
c4-->Publicaciones_revisadas :si
Publicaciones_revisadas-->[*] :Cerrar sesión
c4--> Visualizar_publicaciones :no
Añadir_publicaciones-->c5: verificar publicación?
c5-->Consultar_lista_actividades_proyectos :si
c5-->Consultar_calendario_eventos :no
Consultar_lista_actividades_proyectos-->c6:Aprobar?
c6-->Actualizar_calendaro_eventos :si
c6-->Notificar_al_usuario :no
Notificar_al_usuario-->c2
Consultar_calendario_eventos-->c7:Agregar evento?
c7-->Actualizar_calendaro_eventos :si
c7--> Visualizar_publicaciones :no


@enduml