@startuml Diagrama de Estado Proyecto
state c1 <<choice>>
state c2 <<choice>>
state c3 <<choice>>
state c4 <<choice>>
state c5 <<choice>>
state c6 <<choice>>
state c7 <<choice>>

[*] --> Entrando_a_plataforma: Iniciar espacio virtual
Entrando_a_plataforma-->c1:Registrar?
c1-->Ingresando_datos :si
c1-->Iniciando_sesión :no
Ingresando_datos-->Iniciando_sesión
Iniciando_sesión-->c2:Consultar publicaciones?
c2-->Visualizando_publicaciones :si
c2--> Añadiendo_publicaciones :no
Visualizando_publicaciones-->c3:Comentar?
c3-->Notificando_de_publicación :si
c3-->Continuando_navegación :no
Notificando_de_publicación-->c4
Continuando_navegación-->c4:Eventos revisados?
c4-->Terminando_de_revisar_publicaciones :si
Terminando_de_revisar_publicaciones-->[*] :Cerrar sesión
c4--> Visualizando_publicaciones :no
Añadiendo_publicaciones-->c5: verificar publicación?
c5-->Consultando_lista_actividades_proyectos :si
c5-->Consultando_calendario_de_eventos :no
Consultando_lista_actividades_proyectos-->c6:Aprobar?
c6-->Actualizando_calendario_de_eventos :si
Actualizando_calendario_de_eventos-->Continuando_navegación
c6-->Notificando_al_usuario :no
Notificando_al_usuario-->c2
Consultando_calendario_de_eventos-->c7:Agregar evento?
c7-->Actualizando_calendario_de_eventos :si
c7--> Visualizando_publicaciones :no


@enduml